name: Study Reviews

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Clean build directory
        run: rm -rf _site

      - name: Copy generated files to docs
        run: |
          cp generated/study-guide-complete.md docs/
          cp generated/study-guide-printable.md docs/

      - name: Install dependencies
        run: |
          cd docs
          bundle install

      - name: Build with Jekyll
        run: |
          cd docs
          bundle exec jekyll build --destination ../_site

      - name: Upload site content
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
