name: Generate Study Guide Versions

on:
  push:
    branches: ["main"]
    paths: ["docs/**/*.md"]
  pull_request:
    branches: ["main"]
    paths: ["docs/**/*.md"]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Generate combined versions
        run: |
          python3 scripts/generate_versions.py
      
      - name: Upload generated files
        uses: actions/upload-artifact@v3
        with:
          name: study-guide-versions
          path: |
            generated/study-guide-printable.md
            generated/study-guide-complete.md
      
      - name: Create Pull Request for complete version
        if: github.ref == 'refs/heads/main'
        run: |
          # Copy the complete version to docs directory
          cp generated/study-guide-complete.md docs/study-guide-complete.md
          
          # Add and commit the file
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/study-guide-complete.md
          git commit -m "Add complete study guide version" || echo "No changes to commit"
          git push origin main || echo "Push failed or no changes"
